language: node_js
node_js:
- '8'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn bootstrap
- yarn lint
- yarn test
- yarn build-storybook
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- travis_wait node scripts/run-ndla-script.js now-travis --static packages/designmanual/storybook-static --local-config ./now.json
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: WNfcwzr+3A/WTIkYjrrM5d90+UByJG+w8ziuTM0/Bm3CihpO72/GZVmBant9/GRBlA1O+Xtm+Ll4QHmsP8ICtwtYcX25nnJznf5/XsanYicyfjqtsJfdLCthfX4QaJNoIPr9oY+B2cG/1va5fBDjl7FOU9PctfimakhhACbvJb96N7q+ANgh9uNxHVPIHFX1Enq+eML+Cah0knx3M8pvnEKVnBkB18dbb6hkievzFiVym92141lDMzc7StD9WHklyp6at7f51ZBpIF/COAc+dBkJs4f3jRhhH2hvUW0J2oyXYHeU7LOIY9TtQJqQdsa2AmqBSGV8LRk4FdK8FvkdU32MgvfoElwgSRpIXJYtUwpfuwnjBNLCScsj41v9yb5eQ/T2AT370tn6TBMu3xJLPJij7Ph0WeZ03OOynldnNFz4jJyGtcQnOsiyIiDqp1n+K2RzmO8e0Gm0GHuMAudHL0I8NTfoY7ZUZlBgSf9czj0m6Ig2MsZMdjzcI83GT0n/oxvzPxIrG+kt4Msj8roPpiVTpH+gS1wsYnGf8UflGc6xagtKM40ytO0SWjFKWbXeOvweNhgI8rf9aWqX6zNh1A/XSu/Ln6mefUQQ/h56b4Jni8EMQGHCZYX6VJJm7JyWGV6Sf7Wy9A85fW0L3Ca+NrYhQN7aRUGRGmdzHVriDEE=
env:
  global:
    secure: GmFpStEohFxfSNucOEyC8YMycZnTzTs66240/4mgfeQ9EJxsmduShuAzZT2wr3TSn1IUqYG/u8bYi13qEVPrQFK4OT2npG+Bbuu0yEeFbWVVGTGC9ZTGEuDNNltfa3LPStQVL2MULzvIjsKnbYcqwyACKlL8e38ODbbqIVJpwZ2PRdVqzquN2VOUT0rRZDYj6lHg+hEUkg66QOTErGKhVpMRdpu/hhB5fewEekH6YQHInhV9HjaqJdVJpNOx8YvJpSrDbp5JO6MZjORD+oZFlLipusQZVvauY+DIy4Igzolho0q/llDByTHotxrTcGoVLny+7faqL3v6dXV+uF7TpuupFoQYsbLgwP5EPtZx4EYZJJE80yVc/HAiX15KkeUUOEb1nvwdhs6IsW+ZWcNedizC1ZVMdEdCwoIsZ3kyCZPA5MGRhrDyFhFUOMAbaExu3oV2C60TojdNKv9PtJrqj4pSauOt7SynPeElv5baLqqI9SFNSsNFJY97el/hs6quQwyR9WR1ned0rUAuGYamHGuGs2mlULs8lJkL9P2sv0uWdDbUyubxDAKSTcnXPEAh2X16U0rEhbbrFrsu1RRH/zi2ZrvUgkR52w1B7QnnvS7jvO6oB+YimfQR6VHtmjnnXUbf+gQG7HJ9xWwXJvmZhDxde9ivzqU9A3iB4i5z4GY=
